# Generated by Django 4.0.5 on 2022-06-29 15:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/images')),
                ('title', models.CharField(max_length=50)),
                ('body', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب',
                'ordering': ('-created_at',),
            },
        ),
    ]
