# Generated by Django 4.0.5 on 2022-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='welcome/images')),
                ('welcome', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
    ]
