# Generated by Django 4.0.5 on 2022-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AddField(
            model_name='aboutme',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
