# Generated by Django 4.0.5 on 2022-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_aboutme_options_aboutme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
