# Generated by Django 4.0.5 on 2022-06-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_aboutme_foreword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_me/images')),
                ('question', models.CharField(max_length=80)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='foreword',
            options={'verbose_name': 'پیشگفتار', 'verbose_name_plural': 'پیشگفتار'},
        ),
    ]
