# Generated by Django 4.0.5 on 2022-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutme_alter_foreword_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.CharField(max_length=5000)),
                ('being_printed', models.CharField(max_length=5000)),
                ('sold_volume', models.CharField(max_length=5000)),
                ('idea', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'شمارشگر',
                'verbose_name_plural': 'شمارشگر',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterModelOptions(
            name='foreword',
            options={'verbose_name': 'خانه', 'verbose_name_plural': 'خانه'},
        ),
    ]
