# Generated by Django 4.0.5 on 2022-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
