# Generated by Django 4.0.5 on 2022-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_slider/images'),
        ),
    ]
