# Generated by Django 4.0.5 on 2022-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bookslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslider',
            name='image',
            field=models.ImageField(upload_to='book_slider/images'),
        ),
    ]
