# Generated by Django 4.0.5 on 2022-06-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_book_name_bookslider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('activity', models.TextField()),
            ],
            options={
                'verbose_name': 'فعلیت های فرهنگی',
                'verbose_name_plural': 'فعالیت های فرهنگی',
            },
        ),
        migrations.AlterModelOptions(
            name='bookslider',
            options={'verbose_name': 'اسلایدر کتابها', 'verbose_name_plural': 'اسلایدر کتابها'},
        ),
    ]
