# Generated by Django 4.0.5 on 2022-06-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_culturalactivity_alter_bookslider_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cultural/images'),
        ),
    ]
