# Generated by Django 4.0.5 on 2022-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_culturalactivity_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturalactivity',
            options={'ordering': ('-title',), 'verbose_name': 'فعلیت های فرهنگی', 'verbose_name_plural': 'فعالیت های فرهنگی'},
        ),
    ]
