# Generated by Django 4.0.5 on 2022-06-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_culturalactivity_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSlider',
        ),
    ]
