# Generated by Django 4.0.5 on 2022-06-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیو'},
        ),
    ]
