# Generated by Django 4.0.5 on 2022-06-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='title',
            new_name='name',
        ),
    ]
