# Generated by Django 4.0.5 on 2022-06-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_title_contactus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
