# Generated by Django 4.0.5 on 2022-06-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'پیام ها', 'verbose_name_plural': 'پیام'},
        ),
        migrations.AlterModelOptions(
            name='culturalactivity',
            options={'ordering': ('-title',), 'verbose_name': 'فعالیت های فرهنگی', 'verbose_name_plural': 'فعالیت های فرهنگی'},
        ),
        migrations.AlterModelOptions(
            name='foreword',
            options={'verbose_name': 'معرفی', 'verbose_name_plural': 'معرفی'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'شبکه های اجتماعی', 'verbose_name_plural': 'شبکه اجتماعی'},
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(upload_to='about_me/images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='question',
            field=models.CharField(max_length=80, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='countup',
            name='being_printed',
            field=models.CharField(max_length=5000, verbose_name='کتاب های در دست چاپ'),
        ),
        migrations.AlterField(
            model_name='countup',
            name='idea',
            field=models.CharField(max_length=5000, verbose_name='ایده های کار نشده'),
        ),
        migrations.AlterField(
            model_name='countup',
            name='published',
            field=models.CharField(max_length=5000, verbose_name='کتاب های منتشر شده'),
        ),
        migrations.AlterField(
            model_name='countup',
            name='sold_volume',
            field=models.CharField(max_length=5000, verbose_name='جلدهای فروخته شده'),
        ),
        migrations.AlterField(
            model_name='culturalactivity',
            name='activity',
            field=models.TextField(verbose_name='فعالیت'),
        ),
        migrations.AlterField(
            model_name='culturalactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cultural/images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='culturalactivity',
            name='title',
            field=models.CharField(max_length=150, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='foreword',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='foreword',
            name='image',
            field=models.ImageField(upload_to='welcome/images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='foreword',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='foreword',
            name='welcome',
            field=models.CharField(max_length=400, verbose_name='متن خوش آمد گویی'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='نام شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='target',
            name='question',
            field=models.CharField(max_length=100, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='target',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='target',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='images/Video', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='لینک'),
        ),
    ]
