# Generated by Django 4.0.5 on 2022-07-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(upload_to='images/about_me', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='culturalactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cultural', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='foreword',
            name='image',
            field=models.ImageField(upload_to='images/welcome', verbose_name='تصویر'),
        ),
    ]
